### ISSUE TITLE
Bin Height units different than original gridfinity 

### ISSUE THREAD

**Issue by LampeMW** [Le0Michine/FusionGridfinityGenerator#24]
Maybe I'm misunderstanding something, but in order to create a bin that matches an existing one created by Zack Freedman, I have to set the Bin Height (u) to one less than Zack's. I printed a bunch of 1x1x3 bins, and when I create a 1x1x3 in Fusion 360 using this plugin it's 7mm taller than the 1x1x3s I printed. So I have to create it in Fusion as a 1x1x2 instead, and then it's the correct height.

**Comment by tnoppeney** [comment]
I noticed this as well, but was not sure if it is the correct behavior (it's the first time I printed gridfinity bins). I was confused that 3 stacked bins with heights 4+3+3 are not the same than 2 stacked bins with heights 5+5. For any of those calculations you have to basically add 1 to the selected height of each bin. So 2 bins with height 5 are not equal to 10 "units" but 12 and that way have stacked the same height as 3 bins with height 3 (each actually equal to 4 "units", so that in the end 3x4 also results in a height of 12 "units"). I hope that is understandable.

**Comment by schneems** [comment]
I came here to say the same thing these are both height 8 bins. The black are "height 8" from this fusion plugin. The white are "height 8" from the open scad https://www.printables.com/model/174346-gridfinity-openscad-model.

![2023-05-02 07 18 00](https://user-images.githubusercontent.com/59744/235691260-9a5073b8-2a3d-45a3-8b79-5a21f13ebf29.jpg)

@tnoppeney the height should be 7mm x height + 3.75. So a h8 should be `7 * 8 + 3.75 = 59.75mm`

**Comment by diybytes** [comment]
The plugin-calculated bin height is 1U taller than the specification. For example the default 5U bin setting (without stacking lip) should give a height of 35mm, whereas the plugin calculates 42mm. The gridfinity specification [here](https://www.printables.com/model/417152-gridfinity-specification) and [here](https://gridfinity.xyz/specification/) suggest that the first unit _includes_ the 4.75mm base profile, contrary to @schneems maths above.

**Comment by Le0Michine** [comment]
thanks for reporting the issue, updated bin height calculation so it should match entered values now

**Comment by schneems** [comment]
Thank you!
