### ISSUE TITLE
Gridfinity bin not appearing in create menu

### ISSUE THREAD

**Issue by vdruelle** [Le0Michine/FusionGridfinityGenerator#25]
Hi, thanks for creating this add-in ! Unfortunately importing the add-in in Fusion360 does not seem to work for me.
I installed by reproducing the steps in the README (went for the zip option) and then imported from Fusion as shown below:
![image](https://user-images.githubusercontent.com/60902073/235295204-41654f1b-630b-4837-bd87-d7f9126b83b4.png)

Something does not seem to work because the "gridfinity bin" and "gridfinity baseplate" do not appear in the menu afterwards:
![image](https://user-images.githubusercontent.com/60902073/235295231-b1fbdaff-6e3c-415a-8e2c-5054f848ae43.png)

Hoping that this might be due to recent changes I also tried with older versions (commits 188c3993d81eaab9fc46f85b9ea3c13d90981874 and a488e96d15b31110b5020621042c36720f704ce4) but got the same problem. Any idea on how to solve this ?

System informations:
Fusion 360 2.0.16007 x86_64
Microsoft Windows 11 Family version 10.0.22621

**Comment by Le0Michine** [comment]
Hi, the first screenshot seems to suggest you selected "create addin" rather than plus button to import it, could you confirm if that was the case?
Also please validate if folder specified on the screenshot contains everything from the repository, it should have GridfinityGenerator.manifest and other files/folders in it at that level

![image](https://user-images.githubusercontent.com/2707008/236683385-166051d0-6df8-493f-8d61-f2447b4795c5.png)

**Comment by vdruelle** [comment]
Hi,

I removed my first addition of the add-in and made sure to select the right folder and add via the "+". It seems to have fixed the issue as the things appear correctly in the menu. 

Thank you for the help !
