### ISSUE TITLE
Possibilty to add half X or Y 

### ISSUE THREAD

**Issue by sosher** [Le0Michine/FusionGridfinityGenerator#4]
Hi thanks  for great work, Sometime Half is half as good :) 
would it possible to create half grid \ bin ?

**Comment by Le0Michine** [comment]
Hi, can you clarify the request? Do you want to be able to create smaller grid or is it about something else?

**Comment by sosher** [comment]
sorry for the late response, Since I lack the proper description skills a picture is worth a thousands prints 
https://www.printables.com/model/241907-gridfinity-half-box

**Comment by Le0Michine** [comment]
it seems right now a very similar result can be achieved with setting base size to half (21mm)

![image](https://user-images.githubusercontent.com/2707008/224915215-8016549a-018a-4f28-90dc-90183fe0dbfa.png)

**Comment by Le0Michine** [comment]
but since I already did some work decoupling width and length for the base I don't see an issue in exposing it, check out latest version it should have it now

though it seems like holes pattern isn't gonna work with either of the options, they are currently not editable

![image](https://user-images.githubusercontent.com/2707008/224915731-57fb5a63-8047-4a5c-8815-5ec0dc5b047b.png)

**Comment by Le0Michine** [comment]
and with tab width customization you should be able to get a close match 
![image](https://user-images.githubusercontent.com/2707008/224917129-80878767-43ab-4ae5-b029-020f7b7f5147.png)

**Comment by sosher** [comment]
Awesome, Will check it today, Thanks for the attention.

**Comment by Le0Michine** [comment]
I'm gonna close the issue, feel free to reopen or create a new one if you run into issues
