### ISSUE TITLE
Reset inputs (right now)?

### ISSUE THREAD

**Issue by Nickduino** [Le0Michine/FusionGridfinityGenerator#63]
I like the fact you can choose to preserve the parameters for the next bin but what if the next time you'd rather start from zero? Or what if you'd like to reuse your last parameters but forgot to check the box the last time?

To solve that, I think the ideal would be to always keep the parameters (so you never forget to check the box) and have a button to reset them back to default if you want to.

**Comment by Le0Michine** [comment]
Hi, thanks for creating this request. Currently I'm working on improvements to that functionality and the initial implementation will have three buttons instead of radio as shown below. It looks like it should cover this request, please let me know if you have a different use case

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/0ac1fe63-0d40-4d18-ae2b-0efa82ad0fb4)

**Comment by Nickduino** [comment]
I like this implementation and understand it. I think the labels could be clearer, though.

I would prefer "go back to default" or "return to default" or "load previously saved" as the term "reset" tends to mean "go back to factory".

Here's a proposal for all three choices:
- save current parameters
- load previous parameters
- reset parameters

**Comment by Nickduino** [comment]
**Or** you save the last input and offer one "reset parameters" button. That's simpler in my opinion and you don't loose much functionality

**Comment by Le0Michine** [comment]
thanks for the feedback, will think about it and see if something could be improved before release
